services:
  browser-mcp:
    # image: zenkiet/browser:${BROWSER_MCP_TAG}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:${BROWSER_MCP_PORT}:8000
    shm_size: "1gb"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - MODEL_NAME=${MODEL_NAME}
      - BROWSER_MCP_HOST=0.0.0.0
      - BROWSER_MCP_PORT=8000
      - BROWSER_PREWARM=${BROWSER_PREWARM}
    volumes:
      - ${DATA_PATH}/browser-mcp:/data
